### ISSUE TITLE
plot not showing

### ISSUE THREAD

**Issue by danielemarinazzo** [lukassnoek/scanphyslog2bids#1]
Hi, thanks a lot for the tool!
I don't see the plot running the tool from the terminal (Ununtu 18). I have installed all the mentioned dependencies.
Any idea of what I should fix?
thanks!

**Comment by lukassnoek** [comment]
Hi! Did you add the flags `--plottraces` and `--plotalignment` to your command? This should save the plots (in either the `derivdir`, if this is specified in the command, or in the same directory as the SCANPHYSLOG file if not).

**Comment by danielemarinazzo** [comment]
I had tried the former but not the latter. Now I have the png saved.
Thanks!

-- 

Daniele Marinazzo
Department of Data Analysis
Faculty of Psychology and Educational Sciences, Ghent University
Henri Dunantlaan 1, B-9000 Ghent, Belgium

+32 (0) 9 264 6375
http://users.ugent.be/~dmarinaz/

Twitter @dan_marinazzo

http://helpdesk.ugent.be/e-maildisclaimer.php

**Comment by lukassnoek** [comment]
Good to hear!
